name: SignalK Plugin CI

on:
  push:
  pull_request:

jobs:
  test:
    uses: SignalK/signalk-server/.github/workflows/plugin-ci.yml@master
    with:
      build-command: "npm run build"
      format-check-command: "npm run format:check"

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "24"
      - run: npm install
      - run: npm ci
      - run: npm test
